### ISSUE TITLE
Can not find this page in the documentation 

### ISSUE THREAD

**Issue by orena1** [neuronsimulator/progref-py#24]
Hi,
I am probably missing something, but I can not find this page:
https://www.neuron.yale.edu/neuron/static/py_doc/programming/neuronpython.html?highlight=load_mechanisms
in this documentation. I mainly want to add this link:
https://github.com/neuronsimulator/nrn/blob/master/share/lib/hoc/stdrun.hoc#L488

to the neuron.run() command, as it helps to understand how it works. I actually suggest linking each hoc command to the hoc source code.

Thanks

**Comment by ramcdougal** [comment]
Thanks for thinking of this, however those two things are unrelated:

`neuron.run()` should not be used by anybody. It is **not** the same thing as `h.run()` and is **not** coded in HOC, but rather in Python and like basically everything on that page dates from the early days of using Python with NEURON (note the 2007 copyright date shown in one example) and does not represent current usage. We really need to just rework or remove that page.

That said,

The pages in the repository are in 1-1 correspondence with the paths on the server, so the `programming/neuronpython.html` URL corresponds to `programming/neuronpython.rst` file here. If you look at that file, you'll see that it's autogenerated from the docstrings in the neuron module, so the documentation that appears is direct from the *Python* definition of neuron.run, which is at https://github.com/neuronsimulator/nrn/blob/80685c00755a72ee9c635e71f89fd0b56f89dca3/share/lib/python/neuron/__init__.py#L387

**Comment by orena1** [comment]
Got it, thanks for the explanation.

Do note, that h.run() does not pop-out in the search, but instead neuron.run(). As I see that neuron.run() is without initialization, I think it should be good to remove it from the search or at least move h.run() to the beginning. Alos to add a warning that neuron.run() should not be used, and that h.run() is probably what one is searching for + a link to the function.

![image](https://user-images.githubusercontent.com/8983713/83973709-e53fc300-a8f0-11ea-8f34-8f6ab60146c6.png)

Thanks

**Comment by ramcdougal** [comment]
The broader issue here is that with a few exceptions, only the built-in functions are documented in the programmer's reference; essentially none of the standard HOC library is documented. (`h.run()` is only defined if you've done an `h.load_file('stdrun.hoc')` or something that loads that library, like importing `gui`.)

Don't get me wrong, I agree the library should be documented, but... There are 123 HOC files in the standard library, which is a lot of functions and classes. `stdrun.hoc` and `stdlib.hoc` are reasonable starting places, but I don't really know how I'd meaningfully start trying to document all of these. Contributions welcome. :)

In terms of best practice: as per the Zen of Python (Tim Peters), "explicit is better than implicit." `h.run()` implicitly uses two global variables. Instead of using that function, in the NEURON course we recommend explicitly initializing and then doing a continuerun instead of using a run. That is, assuming you've done a

    from neuron import h
    from neuron.units import mV, ms
    h.load_file('stdrun.hoc')

when it's time to run, you'd want to

    h.finitialize(-65 * mV)
    h.continuerun(100 * ms)

and then there are no mysterious global variables acting behind the scenes.

**Comment by orena1** [comment]
I understand, but from my experience, many people use run().
I suggest to at least add a warning in the neuron.run()..

Thank you for the information.

**Comment by ramcdougal** [comment]
How do you feel about https://github.com/neuronsimulator/nrn/pull/585

**Comment by orena1** [comment]
Looks good, thanks.

By the way, a bit offtopic. Look at this nice hack, for progress bar :
```
tct = '''
proc continuerun() {local rt, rtstart, ts
	realtime = 0  rt = screen_update_invl  rtstart = startsw()
	eventcount=0
	eventslow=1
	stoprun = 0
	if (using_cvode_) {
		cvode.event($1)
		ts = $1
		if (cvode.use_local_dt) {
			cvode.solve(ts)
			flushPlot()
			realtime = startsw() - rtstart
			return
		}
	}else{
		ts = $1 - dt/2
	}
    nrnpython("from tqdm.notebook import trange, tqdm")
    nrnpython("pbar = tqdm(total=h.tstop)")
    nrnpython("last_t = h.t")
	while(t < ts && stoprun == 0) {
		step()

		realtime = startsw() - rtstart
		if (realtime >= rt) {
//			if (!stdrun_quiet) fastflushPlot()
			screen_update()
            nrnpython("pbar.update(h.t-last_t)")
            nrnpython("last_t=h.t")
            //really compute for at least screen_update_invl
			realtime = startsw() - rtstart
			rt = realtime + screen_update_invl
		}
	}
	if (using_cvode_ && stoprun == 0) { // handle the "tstop" event
		step() // so all recordings take place at tstop
	}
	flushPlot()
	realtime = startsw() - rtstart
}
'''
h(tct)
```

**Comment by ramcdougal** [comment]
That's cool. I like `tqdm` but had never thought to do that.

One minor suggestion: your definition of `pbar` assumes that you're running for `h.tstop` but this variable need not have anything to do with the variable `ts` which is the requested runtime. (If you're calling `run`, they'll be the same, but they aren't in general.)

That is, instead of:

    nrnpython("pbar = tqdm(total=h.tstop)")

Use something like:

    sprint(temp_string2_, "pbar = tqdm(total = %g)", ts)
    nrnpython(temp_string2_)

**Comment by ramcdougal** [comment]
Think of `continuerun` as continuing a run until the specified time. That is, if you initialize, you've "ran" to time 0. Then a `continuerun(10)` brings you to time 10, and a `continuerun(15)` continues that simulation (starting from t=10) until time 15.

The fact that it doesn't restart is what makes it something that is "continuing" the run.

It's a weird name for a single simulation, but the name is a bit more intuitive for the case where you want to run for a bit, plot/save things, run a bit more, plot again, etc...

**Comment by orena1** [comment]
I have no problem with the naming, I just think that newcomers might be a bit confused with the name.
Thanks for the info.
